SUBNET_LINKS = [
    {"name": "sn0", "url": ""},
    {"name": "sn1", "url": "https://github.com/opentensor/text-prompting/"},
    {"name": "sn2", "url": "https://github.com/bittranslateio/bittranslate/"},
    {
        "name": "sn3",
        "url": "https://github.com/gitphantomman/scraping_subnet/",
    },
    {"name": "sn4", "url": "https://github.com/manifold-inc/targon/"},
    {"name": "sn5", "url": "https://github.com/unconst/ImageSubnet/"},
    {"name": "sn6", "url": ""},
    {"name": "sn7", "url": "https://github.com/tensorage/tensorage/"},
    {
        "name": "sn8",
        "url": "https://github.com/taoshidev/time-series-prediction-subnet/",
    },
    {"name": "sn9", "url": "https://github.com/unconst/pretrain-subnet/"},
    {
        "name": "sn10",
        "url": "https://github.com/dream-well/map-reduce-subnet/",
    },
    {"name": "sn11", "url": "https://github.com/opentensor/text-prompting/"},
    {"name": "sn12", "url": ""},
    {"name": "sn13", "url": "https://github.com/RusticLuftig/data-universe/"},
    {
        "name": "sn14",
        "url": "https://github.com/ceterum1/llm-defender-subnet/",
    },
    {
        "name": "sn15",
        "url": "https://github.com/blockchain-insights/blockchain-data-subnet/",
    },
    {"name": "sn16", "url": "https://github.com/UncleTensor/AudioSubnet/"},
    {"name": "sn17", "url": "https://github.com/CortexLM/flavia/"},
    {"name": "sn18", "url": "https://github.com/corcel-api/cortex.t/"},
    {"name": "sn19", "url": "https://github.com/namoray/vision/"},
    {"name": "sn20", "url": "https://github.com/oracle-subnet/oracle-subnet/"},
    {"name": "sn21", "url": "https://github.com/ifrit98/storage-subnet/"},
    {"name": "sn22", "url": "https://github.com/surcyf123/smart-scrape/"},
    {"name": "sn23", "url": "https://github.com/NicheTensor/NicheImage/"},
    {"name": "sn24", "url": "https://github.com/eseckft/BitAds.ai/tree/main"},
    {"name": "sn25", "url": "https://github.com/KMFODA/DistributedTraining/"},
    {
        "name": "sn26",
        "url": "https://github.com/Supreme-Emperor-Wang/ImageAlchemy/",
    },
    {
        "name": "sn27",
        "url": "https://github.com/neuralinternet/compute-subnet/",
    },
    {"name": "sn28", "url": "https://github.com/zktensor/zktensor_subnet/"},
    {"name": "sn29", "url": "https://github.com/404-Repo/Subnet-29/"},
    {"name": "sn30", "url": ""},
    {
        "name": "sn31",
        "url": "https://github.com/bthealthcare/healthcare-subnet",
    },
    {"name": "sn32", "url": "https://github.com/RoyalTensor/roleplay/"},
]
