
//! Autogenerated weights for `pallet_referenda`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-04-24, STEPS: `50`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Evgenys-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/production/node-subtensor
// benchmark
// pallet
// --runtime
// target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet
// pallet_referenda
// --extrinsic
// *
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=./
// --template=.maintain/frame-weight-template.hbs
// --steps
// 50
// --repeat
// 5

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_referenda`.
pub trait WeightInfo {
    fn submit() -> Weight;
    fn cancel() -> Weight;
    fn nudge_referendum() -> Weight;
}

/// Weights for `pallet_referenda` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Referenda::OngoingPerTrack` (r:1 w:1)
    /// Proof: `Referenda::OngoingPerTrack` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::ReferendumCount` (r:1 w:1)
    /// Proof: `Referenda::ReferendumCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Lookup` (r:1 w:1)
    /// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Agenda` (r:1 w:1)
    /// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10463), added: 12938, mode: `MaxEncodedLen`)
    /// Storage: `MultiCollective::Members` (r:1 w:0)
    /// Proof: `MultiCollective::Members` (`max_values`: None, `max_size`: Some(658), added: 3133, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::ReferendumStatusFor` (r:0 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:0 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:0 w:1)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    fn submit() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `126`
        //  Estimated: `13928`
        // Minimum execution time: 24_000_000 picoseconds.
        Weight::from_parts(24_000_000, 13928)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Lookup` (r:1 w:1)
    /// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Agenda` (r:1 w:1)
    /// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10463), added: 12938, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::OngoingPerTrack` (r:1 w:1)
    /// Proof: `Referenda::OngoingPerTrack` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:0 w:1)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    fn cancel() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `505`
        //  Estimated: `13928`
        // Minimum execution time: 33_000_000 picoseconds.
        Weight::from_parts(33_000_000, 13928)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::OngoingPerTrack` (r:1 w:1)
    /// Proof: `Referenda::OngoingPerTrack` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:0 w:1)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    fn nudge_referendum() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `308`
        //  Estimated: `3646`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 3646)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    /// Storage: `Referenda::OngoingPerTrack` (r:1 w:1)
    /// Proof: `Referenda::OngoingPerTrack` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::ReferendumCount` (r:1 w:1)
    /// Proof: `Referenda::ReferendumCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Lookup` (r:1 w:1)
    /// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Agenda` (r:1 w:1)
    /// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10463), added: 12938, mode: `MaxEncodedLen`)
    /// Storage: `MultiCollective::Members` (r:1 w:0)
    /// Proof: `MultiCollective::Members` (`max_values`: None, `max_size`: Some(658), added: 3133, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::ReferendumStatusFor` (r:0 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:0 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:0 w:1)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    fn submit() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `126`
        //  Estimated: `13928`
        // Minimum execution time: 24_000_000 picoseconds.
        Weight::from_parts(24_000_000, 13928)
            .saturating_add(ParityDbWeight::get().reads(5_u64))
            .saturating_add(ParityDbWeight::get().writes(7_u64))
    }
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Lookup` (r:1 w:1)
    /// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Scheduler::Agenda` (r:1 w:1)
    /// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10463), added: 12938, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::OngoingPerTrack` (r:1 w:1)
    /// Proof: `Referenda::OngoingPerTrack` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:0 w:1)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    fn cancel() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `505`
        //  Estimated: `13928`
        // Minimum execution time: 33_000_000 picoseconds.
        Weight::from_parts(33_000_000, 13928)
            .saturating_add(ParityDbWeight::get().reads(5_u64))
            .saturating_add(ParityDbWeight::get().writes(6_u64))
    }
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `Referenda::OngoingPerTrack` (r:1 w:1)
    /// Proof: `Referenda::OngoingPerTrack` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:0 w:1)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    fn nudge_referendum() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `308`
        //  Estimated: `3646`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 3646)
            .saturating_add(ParityDbWeight::get().reads(3_u64))
            .saturating_add(ParityDbWeight::get().writes(4_u64))
    }
}
