ARG BASE_IMAGE=ubuntu:latest

FROM $BASE_IMAGE AS builder
SHELL ["/bin/bash", "-c"]

# Set noninteractive mode for apt-get
ARG DEBIAN_FRONTEND=noninteractive

LABEL ai.opentensor.image.authors="operations@opentensor.ai" \
  ai.opentensor.image.vendor="Opentensor Foundation" \
  ai.opentensor.image.title="opentensor/subtensor-localnet" \
  ai.opentensor.image.description="Opentensor Subtensor Blockchain" \
  ai.opentensor.image.documentation="https://docs.bittensor.com"

# Set up Rust environment
ENV RUST_BACKTRACE=1

RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirrors.edge.kernel.org/ubuntu|g' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y curl build-essential protobuf-compiler clang git pkg-config libssl-dev llvm libudev-dev

# Copy entire repository
COPY . /build
WORKDIR /build

# Install Rust
RUN set -o pipefail && curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup toolchain install 1.88.0
RUN rustup default 1.88.0''
RUN rustup target add wasm32v1-none

## Build fast-runtime node
RUN ./scripts/localnet.sh --build-only
# Build non-fast-runtime
RUN ./scripts/localnet.sh False --build-only

# Verify the binaries was produced
RUN test -e /build/target/fast-runtime/release/node-subtensor
RUN test -e /build/target/non-fast-runtime/release/node-subtensor

FROM $BASE_IMAGE AS subtensor-localnet

# Copy binaries
COPY --from=builder /build/target/fast-runtime/release/node-subtensor target/fast-runtime/release/node-subtensor
RUN chmod +x target/fast-runtime/release/node-subtensor

COPY --from=builder /build/target/non-fast-runtime/release/node-subtensor target/non-fast-runtime/release/node-subtensor
RUN chmod +x target/non-fast-runtime/release/node-subtensor

COPY --from=builder /build/snapshot.json /snapshot.json

COPY --from=builder /build/scripts/localnet.sh scripts/localnet.sh
RUN chmod +x /scripts/localnet.sh

# Copy WebAssembly artifacts
COPY --from=builder /build/target/fast-runtime/release/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm target/fast-runtime/release/node_subtensor_runtime.compact.compressed.wasm
COPY --from=builder /build/target/non-fast-runtime/release/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm target/non-fast-runtime/release/node_subtensor_runtime.compact.compressed.wasm

## Ubdate certificates
RUN apt-get update && apt-get install -y ca-certificates

# Do not build (just run)
ENV BUILD_BINARY=0
# Switch to local run with IP 0.0.0.0 within docker image
ENV RUN_IN_DOCKER=1
# Expose ports
EXPOSE 30334 30335 9944 9945

ENTRYPOINT ["/scripts/localnet.sh"]
# Fast blocks defaults to True, you can disable it by passing False to the docker command, e.g.:
# docker run ghcr.io/opentensor/subtensor-localnet False
CMD ["True"]
