./target/prod/production/node-subtensor \
  --chain chainspecs/raw_spec_finney.json \
  --base-path /home/blockchain/node0 \
  --sync=full \
  --pruning archive \
  --port 30300 \
  --max-runtime-instances 32 \
  --rpc-max-response-size 1024 \
  --rpc-max-request-size 1024 \
  --rpc-cors all \
  --rpc-port 9900 \
  --bootnodes /dns/bootnode.finney.chain.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
  --in-peers 100 \
  --out-peers 100 \
  --trie-cache-size 8192 \
  --rpc-max-connections 500 \
  --no-prometheus