[package]
name = "procedural-fork"
version = "1.10.0-rc3"
edition = "2021"

[lints.clippy]
all = "allow"

[dependencies]
derive-syn-parse = "0.2"
Inflector = "0.11"
cfg-expr = "0.15"
itertools = "0.10"
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
macro_magic = { version = "0.5", features = ["proc_support"] }
frame-support-procedural-tools = { version = "10.0.0" }
proc-macro-warning = { version = "1", default-features = false }
expander = "2"
sp-crypto-hashing = { default-features = false, version = "0.1.0" }

[dev-dependencies]
regex = "1"

[features]
default = ["std"]
std = ["sp-crypto-hashing/std"]
no-metadata-docs = []
experimental = []
# Generate impl-trait for tuples with the given number of tuples. Will be needed as the number of
# pallets in a runtime grows. Does increase the compile time!
tuples-96 = []
tuples-128 = []
