
//! Autogenerated weights for `pallet_signed_voting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-04-24, STEPS: `50`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Evgenys-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/production/node-subtensor
// benchmark
// pallet
// --runtime
// target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet
// pallet_signed_voting
// --extrinsic
// *
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=./
// --template=.maintain/frame-weight-template.hbs
// --steps
// 50
// --repeat
// 5

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_signed_voting`.
pub trait WeightInfo {
    fn vote() -> Weight;
    fn remove_vote() -> Weight;
}

/// Weights for `pallet_signed_voting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:1 w:0)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VotingFor` (r:1 w:1)
    /// Proof: `SignedVoting::VotingFor` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn vote() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `299`
        //  Estimated: `5527`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 5527)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:1 w:0)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VotingFor` (r:1 w:1)
    /// Proof: `SignedVoting::VotingFor` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn remove_vote() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `374`
        //  Estimated: `5527`
        // Minimum execution time: 22_000_000 picoseconds.
        Weight::from_parts(24_000_000, 5527)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:1 w:0)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VotingFor` (r:1 w:1)
    /// Proof: `SignedVoting::VotingFor` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn vote() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `299`
        //  Estimated: `5527`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 5527)
            .saturating_add(ParityDbWeight::get().reads(4_u64))
            .saturating_add(ParityDbWeight::get().writes(3_u64))
    }
    /// Storage: `Referenda::ReferendumStatusFor` (r:1 w:1)
    /// Proof: `Referenda::ReferendumStatusFor` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VoterSnapshot` (r:1 w:0)
    /// Proof: `SignedVoting::VoterSnapshot` (`max_values`: None, `max_size`: Some(2062), added: 4537, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::TallyOf` (r:1 w:1)
    /// Proof: `SignedVoting::TallyOf` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `SignedVoting::VotingFor` (r:1 w:1)
    /// Proof: `SignedVoting::VotingFor` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn remove_vote() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `374`
        //  Estimated: `5527`
        // Minimum execution time: 22_000_000 picoseconds.
        Weight::from_parts(24_000_000, 5527)
            .saturating_add(ParityDbWeight::get().reads(4_u64))
            .saturating_add(ParityDbWeight::get().writes(3_u64))
    }
}
