#!/usr/bin/env bash
# vim: noexpandtab shiftwidth=2 tabstop=2
#
# Author: S0AndS0
# Description: Check and possibly format only Rust files that were recently committed 
# Note: Utilizes nightly features to mitigate extraneous changes
#
# **Warnings**
# - Unstaged hunks in files formatted with this hook will be tracked
#
# **Example usage**
#
# ```bash
# git commit src/some-file.rs
#
# VERBOSE=1 git commit src/another-file.rs
# ```
##

set -EeT

__hey_listen__() {
	if (( VERBOSE )); then
		printf '%s\n' "${@}"
	fi
}

while read -r _path; do
	if rustup run nightly -- rustfmt --check --quiet -- "${_path}" 1>/dev/null 2>&1; then
		__hey_listen__ "Skipping -> ${_path}"
		continue 1
	else
		__hey_listen__ "Formatting -> ${_path}"
		rustup run nightly -- rustfmt -- "${_path}" 1>/dev/null 2>&1
		git add "${_path}"
	fi
done < <(git diff --name-only -r HEAD^1 -- '*.rs')

if ! git diff --name-only --staged --quiet; then
	__hey_listen__ 'Committing format changes'
	git commit --no-verify -F- <<EOF
:robot: :butter: Reformat source code
EOF

	printf >&2 'WARNING: formatting changed please -> git push'
fi
