#!/usr/bin/env bash
# vim: noexpandtab shiftwidth=2 tabstop=2
#
# Author: S0AndS0
# Description: Run tests when Rust source code was committed and not yet tracked by remote
#
# **Warnings**
# - May fail if HEAD is detached
#
# **Example usage**
#
# ```bash
# VERBOSE=1 git commit src/some-file.rs
#
# git push
# ```
##

export PATH="$HOME/.cargo/bin:$PATH"

set -EeT

__hey_listen__() {
	if (( VERBOSE )); then
		printf '%s\n' "${@}"
	fi
}

_local_branch="$(git branch --show-current)"
_remote_branch="origin/${_local_branch}"

if git diff --name-only --quiet "${_remote_branch}".."${_local_branch}" -- '*.rs'; then
	__hey_listen__ 'Skipping -> cargo test'
else
	__hey_listen__ 'Running -> cargo test'
	cargo test
fi
