#!/usr/bin/env bash
# vim: noexpandtab shiftwidth=2 tabstop=2
#
# Author: S0AndS0
# Description: Run checks only if/when Rust source code is about to be committed
#
# **Example usage**
#
# ```bash
# VERBOSE=1 git commit src/some-file.rs
# ```
##

set -EeT

__hey_listen__() {
	if (( VERBOSE )); then
		printf '%s\n' "${@}"
	fi
}

if git diff --name-only --staged --quiet -- '*.rs'; then
	__hey_listen__ 'Skipping -> cargo check'
else
	__hey_listen__ 'Running -> cargo check'
	cargo check
fi
