packages:
  - shared
  - shield

catalog:
  "@noble/ciphers": "^2.1.1"
  "@polkadot/keyring": "^14.0.1"
  "@polkadot/util": "^14.0.1"
  "@polkadot/util-crypto": "^14.0.1"
  "@polkadot-labs/hdkd": "^0.0.25"
  "@polkadot-labs/hdkd-helpers": "^0.0.25"
  "@types/node": "^24"
  "mlkem": "^2.5.0"
  "polkadot-api": "^1.22.0"
  "prettier": "^3.0.0"
  "vitest": "^4.0.0"
