
//! Autogenerated weights for `pallet_limit_orders`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-06-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm3jyl0`, CPU: `AMD EPYC 9V74 80-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/runner/work/subtensor/subtensor/target/production/node-subtensor
// benchmark
// pallet
// --runtime=/home/runner/work/subtensor/subtensor/target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet=pallet_limit_orders
// --extrinsic=*
// --steps=50
// --repeat=20
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=/tmp/tmp.h1ZElBJrCs
// --template=/home/runner/work/subtensor/subtensor/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_limit_orders`.
pub trait WeightInfo {
	fn cancel_order() -> Weight;
	fn set_pallet_status() -> Weight;
	fn execute_orders(n: u32, ) -> Weight;
	fn execute_batched_orders(n: u32, ) -> Weight;
}

/// Weights for `pallet_limit_orders` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `LimitOrders::Orders` (r:1 w:1)
	/// Proof: `LimitOrders::Orders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn cancel_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `3522`
		// Minimum execution time: 13_230_000 picoseconds.
		Weight::from_parts(14_822_000, 3522)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LimitOrders::LimitOrdersEnabled` (r:0 w:1)
	/// Proof: `LimitOrders::LimitOrdersEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_pallet_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_006_000 picoseconds.
		Weight::from_parts(4_266_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LimitOrders::LimitOrdersEnabled` (r:1 w:0)
	/// Proof: `LimitOrders::LimitOrdersEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `EVMChainId::ChainId` (r:1 w:0)
	/// Proof: `EVMChainId::ChainId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `LimitOrders::Orders` (r:100 w:100)
	/// Proof: `LimitOrders::Orders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Owner` (r:100 w:0)
	/// Proof: `SubtensorModule::Owner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:202 w:202)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:1)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Swap::FeeRate` (r:1 w:0)
	/// Proof: `Swap::FeeRate` (`max_values`: None, `max_size`: Some(12), added: 2487, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:100 w:100)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:100 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:100 w:100)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:100 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:100 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:100 w:100)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTaoFlow` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTaoFlow` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Lock` (r:100 w:0)
	/// Proof: `SubtensorModule::Lock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (r:0 w:100)
	/// Proof: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn execute_orders(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1134 + n * (283 ±0)`
		//  Estimated: `6148 + n * (5158 ±0)`
		// Minimum execution time: 597_854_000 picoseconds.
		Weight::from_parts(61_768_457, 6148)
			// Standard Error: 136_266
			.saturating_add(Weight::from_parts(520_180_782, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().reads((11_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(10_u64))
			.saturating_add(T::DbWeight::get().writes((7_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5158).saturating_mul(n.into()))
	}
	/// Storage: `LimitOrders::LimitOrdersEnabled` (r:1 w:0)
	/// Proof: `LimitOrders::LimitOrdersEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `EVMChainId::ChainId` (r:1 w:0)
	/// Proof: `EVMChainId::ChainId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `LimitOrders::Orders` (r:100 w:100)
	/// Proof: `LimitOrders::Orders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:203 w:203)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:1)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Swap::FeeRate` (r:1 w:0)
	/// Proof: `Swap::FeeRate` (`max_values`: None, `max_size`: Some(12), added: 2487, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:101 w:101)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:101 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:101 w:101)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:101 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:101 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:101 w:101)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTaoFlow` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTaoFlow` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Lock` (r:1 w:0)
	/// Proof: `SubtensorModule::Lock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Owner` (r:100 w:0)
	/// Proof: `SubtensorModule::Owner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (r:0 w:101)
	/// Proof: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn execute_batched_orders(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1263 + n * (283 ±0)`
		//  Estimated: `8727 + n * (5158 ±0)`
		// Minimum execution time: 747_334_000 picoseconds.
		Weight::from_parts(499_718_496, 8727)
			// Standard Error: 74_442
			.saturating_add(Weight::from_parts(259_134_004, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(25_u64))
			.saturating_add(T::DbWeight::get().reads((10_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(15_u64))
			.saturating_add(T::DbWeight::get().writes((7_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5158).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `LimitOrders::Orders` (r:1 w:1)
	/// Proof: `LimitOrders::Orders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn cancel_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `3522`
		// Minimum execution time: 13_230_000 picoseconds.
		Weight::from_parts(14_822_000, 3522)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `LimitOrders::LimitOrdersEnabled` (r:0 w:1)
	/// Proof: `LimitOrders::LimitOrdersEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_pallet_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_006_000 picoseconds.
		Weight::from_parts(4_266_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `LimitOrders::LimitOrdersEnabled` (r:1 w:0)
	/// Proof: `LimitOrders::LimitOrdersEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `EVMChainId::ChainId` (r:1 w:0)
	/// Proof: `EVMChainId::ChainId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `LimitOrders::Orders` (r:100 w:100)
	/// Proof: `LimitOrders::Orders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Owner` (r:100 w:0)
	/// Proof: `SubtensorModule::Owner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:202 w:202)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:1)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Swap::FeeRate` (r:1 w:0)
	/// Proof: `Swap::FeeRate` (`max_values`: None, `max_size`: Some(12), added: 2487, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:100 w:100)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:100 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:100 w:100)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:100 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:100 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:100 w:100)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTaoFlow` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTaoFlow` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Lock` (r:100 w:0)
	/// Proof: `SubtensorModule::Lock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (r:0 w:100)
	/// Proof: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn execute_orders(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1134 + n * (283 ±0)`
		//  Estimated: `6148 + n * (5158 ±0)`
		// Minimum execution time: 597_854_000 picoseconds.
		Weight::from_parts(61_768_457, 6148)
			// Standard Error: 136_266
			.saturating_add(Weight::from_parts(520_180_782, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().reads((11_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
			.saturating_add(RocksDbWeight::get().writes((7_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5158).saturating_mul(n.into()))
	}
	/// Storage: `LimitOrders::LimitOrdersEnabled` (r:1 w:0)
	/// Proof: `LimitOrders::LimitOrdersEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `EVMChainId::ChainId` (r:1 w:0)
	/// Proof: `EVMChainId::ChainId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `LimitOrders::Orders` (r:100 w:100)
	/// Proof: `LimitOrders::Orders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:203 w:203)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:1)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Swap::FeeRate` (r:1 w:0)
	/// Proof: `Swap::FeeRate` (`max_values`: None, `max_size`: Some(12), added: 2487, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:101 w:101)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:101 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:101 w:101)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:101 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:101 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:101 w:101)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTaoFlow` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTaoFlow` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Lock` (r:1 w:0)
	/// Proof: `SubtensorModule::Lock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Owner` (r:100 w:0)
	/// Proof: `SubtensorModule::Owner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (r:0 w:101)
	/// Proof: `SubtensorModule::LastColdkeyHotkeyStakeBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn execute_batched_orders(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1263 + n * (283 ±0)`
		//  Estimated: `8727 + n * (5158 ±0)`
		// Minimum execution time: 747_334_000 picoseconds.
		Weight::from_parts(499_718_496, 8727)
			// Standard Error: 74_442
			.saturating_add(Weight::from_parts(259_134_004, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(25_u64))
			.saturating_add(RocksDbWeight::get().reads((10_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(15_u64))
			.saturating_add(RocksDbWeight::get().writes((7_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5158).saturating_mul(n.into()))
	}
}
