// Weights for `pallet_subtensor`.
//
// Stubbed entries were auto-generated by weight-stub.
// Re-generate with real values by running benchmarks:
//   ./scripts/benchmark_all.sh pallet_subtensor

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_subtensor`.
pub trait WeightInfo {
	fn register() -> Weight;
	fn set_weights() -> Weight;
	fn add_stake() -> Weight;
	fn serve_axon() -> Weight;
	fn serve_prometheus() -> Weight;
	fn burned_register() -> Weight;
	fn root_register() -> Weight;
	fn register_network() -> Weight;
	fn commit_weights() -> Weight;
	fn reveal_weights() -> Weight;
	fn sudo_set_tx_childkey_take_rate_limit() -> Weight;
	fn set_childkey_take() -> Weight;
	fn announce_coldkey_swap() -> Weight;
	fn swap_coldkey_announced() -> Weight;
	fn swap_coldkey() -> Weight;
	fn dispute_coldkey_swap() -> Weight;
	fn reset_coldkey_swap() -> Weight;
	fn batch_reveal_weights() -> Weight;
	fn recycle_alpha() -> Weight;
	fn burn_alpha() -> Weight;
	fn start_call() -> Weight;
	fn add_stake_limit() -> Weight;
	fn move_stake() -> Weight;
	fn remove_stake_limit() -> Weight;
	fn swap_stake_limit() -> Weight;
	fn transfer_stake() -> Weight;
	fn swap_stake() -> Weight;
	fn batch_commit_weights() -> Weight;
	fn batch_set_weights() -> Weight;
	fn decrease_take() -> Weight;
	fn increase_take() -> Weight;
	fn register_network_with_identity() -> Weight;
	fn serve_axon_tls() -> Weight;
	fn set_identity() -> Weight;
	fn set_subnet_identity() -> Weight;
	fn swap_hotkey() -> Weight;
	fn try_associate_hotkey() -> Weight;
	fn unstake_all() -> Weight;
	fn unstake_all_alpha() -> Weight;
	fn remove_stake_full_limit() -> Weight;
	fn register_leased_network(k: u32) -> Weight;
	fn terminate_lease(k: u32) -> Weight;
	fn update_symbol() -> Weight;
	fn commit_timelocked_weights() -> Weight;
	fn set_coldkey_auto_stake_hotkey() -> Weight;
	fn set_root_claim_type() -> Weight;
	fn claim_root() -> Weight;
	fn sudo_set_num_root_claims() -> Weight;
	fn sudo_set_root_claim_threshold() -> Weight;
	fn add_stake_burn() -> Weight;
}

/// Weights for `pallet_subtensor` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register() -> Weight {
		Weight::from_parts(197_900_000, 0)
			.saturating_add(T::DbWeight::get().reads(24_u64))
			.saturating_add(T::DbWeight::get().writes(20_u64))
	}
	fn set_weights() -> Weight {
		Weight::from_parts(15_540_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(4111_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn add_stake() -> Weight {
		Weight::from_parts(340_800_000, 0)
			.saturating_add(T::DbWeight::get().reads(27_u64))
			.saturating_add(T::DbWeight::get().writes(15_u64))
	}
	fn serve_axon() -> Weight {
		Weight::from_parts(33_010_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn serve_prometheus() -> Weight {
		Weight::from_parts(29_760_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn burned_register() -> Weight {
		Weight::from_parts(354_200_000, 0)
			.saturating_add(T::DbWeight::get().reads(47_u64))
			.saturating_add(T::DbWeight::get().writes(39_u64))
	}
	fn root_register() -> Weight {
		Weight::from_parts(135_900_000, 0)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(16_u64))
	}
	fn register_network() -> Weight {
		Weight::from_parts(235_400_000, 0)
			.saturating_add(T::DbWeight::get().reads(36_u64))
			.saturating_add(T::DbWeight::get().writes(52_u64))
	}
	fn commit_weights() -> Weight {
		Weight::from_parts(67_770_000, 0)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn reveal_weights() -> Weight {
		Weight::from_parts(122_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn sudo_set_tx_childkey_take_rate_limit() -> Weight {
		Weight::from_parts(5_660_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn set_childkey_take() -> Weight {
		Weight::from_parts(66_450_000, 0)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn announce_coldkey_swap() -> Weight {
		Weight::from_parts(55_700_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn swap_coldkey_announced() -> Weight {
		Weight::from_parts(110_700_000, 0)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	fn swap_coldkey() -> Weight {
		Weight::from_parts(161_700_000, 0)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	fn dispute_coldkey_swap() -> Weight {
		Weight::from_parts(30_810_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn reset_coldkey_swap() -> Weight {
		Weight::from_parts(8_977_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn batch_reveal_weights() -> Weight {
		Weight::from_parts(412_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn recycle_alpha() -> Weight {
		Weight::from_parts(113_400_000, 0)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn burn_alpha() -> Weight {
		Weight::from_parts(112_200_000, 0)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn start_call() -> Weight {
		Weight::from_parts(29_780_000, 0)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn add_stake_limit() -> Weight {
		Weight::from_parts(402_900_000, 0)
			.saturating_add(T::DbWeight::get().reads(27_u64))
			.saturating_add(T::DbWeight::get().writes(15_u64))
	}
	fn move_stake() -> Weight {
		Weight::from_parts(164_300_000, 0)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	fn remove_stake_limit() -> Weight {
		Weight::from_parts(377_400_000, 0)
			.saturating_add(T::DbWeight::get().reads(30_u64))
			.saturating_add(T::DbWeight::get().writes(13_u64))
	}
	fn swap_stake_limit() -> Weight {
		Weight::from_parts(411_500_000, 0)
			.saturating_add(T::DbWeight::get().reads(40_u64))
			.saturating_add(T::DbWeight::get().writes(22_u64))
	}
	fn transfer_stake() -> Weight {
		Weight::from_parts(160_300_000, 0)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	fn swap_stake() -> Weight {
		Weight::from_parts(351_300_000, 0)
			.saturating_add(T::DbWeight::get().reads(40_u64))
			.saturating_add(T::DbWeight::get().writes(22_u64))
	}
	fn batch_commit_weights() -> Weight {
		Weight::from_parts(100_500_000, 0)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn batch_set_weights() -> Weight {
		Weight::from_parts(95_460_000, 0)
			.saturating_add(T::DbWeight::get().reads(15_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn decrease_take() -> Weight {
		Weight::from_parts(30_020_000, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn increase_take() -> Weight {
		Weight::from_parts(36_710_000, 0)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn register_network_with_identity() -> Weight {
		Weight::from_parts(396_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(35_u64))
			.saturating_add(T::DbWeight::get().writes(51_u64))
	}
	fn serve_axon_tls() -> Weight {
		Weight::from_parts(32_510_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn set_identity() -> Weight {
		Weight::from_parts(38_230_000, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn set_subnet_identity() -> Weight {
		Weight::from_parts(24_350_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn swap_hotkey() -> Weight {
		Weight::from_parts(275_300_000, 0)
			.saturating_add(T::DbWeight::get().reads(57_u64))
			.saturating_add(T::DbWeight::get().writes(39_u64))
	}
	fn try_associate_hotkey() -> Weight {
		Weight::from_parts(27_150_000, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn unstake_all() -> Weight {
		Weight::from_parts(28_830_000, 0)
			.saturating_add(T::DbWeight::get().reads(6_u64))
	}
	fn unstake_all_alpha() -> Weight {
		Weight::from_parts(358_500_000, 0)
			.saturating_add(T::DbWeight::get().reads(44_u64))
			.saturating_add(T::DbWeight::get().writes(24_u64))
	}
	fn remove_stake_full_limit() -> Weight {
		Weight::from_parts(395_300_000, 10142)
			.saturating_add(T::DbWeight::get().reads(30_u64))
			.saturating_add(T::DbWeight::get().writes(13_u64))
	}
	fn register_leased_network(k: u32) -> Weight {
		Weight::from_parts(301_560_714, 10079)
			.saturating_add(Weight::from_parts(26_884_006, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(41_u64))
			.saturating_add(T::DbWeight::get().reads(2_u64.saturating_mul(k.into())))
			.saturating_add(T::DbWeight::get().writes(55_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64.saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2579).saturating_mul(k.into()))
	}
	fn terminate_lease(k: u32) -> Weight {
		Weight::from_parts(56_635_122, 6148)
			.saturating_add(Weight::from_parts(912_993, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(k.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(k.into()))
	}
	fn update_symbol() -> Weight {
		Weight::from_parts(26_200_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn commit_timelocked_weights() -> Weight {
		Weight::from_parts(94_980_000, 0)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn set_coldkey_auto_stake_hotkey() -> Weight {
		Weight::from_parts(29_930_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn set_root_claim_type() -> Weight {
		Weight::from_parts(19_420_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn claim_root() -> Weight {
		Weight::from_parts(117_000_000, 7767)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn sudo_set_num_root_claims() -> Weight {
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn sudo_set_root_claim_threshold() -> Weight {
		Weight::from_parts(5_711_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn add_stake_burn() -> Weight {
		Weight::from_parts(368_000_000, 8556)
			.saturating_add(T::DbWeight::get().reads(30_u64))
			.saturating_add(T::DbWeight::get().writes(16_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn register() -> Weight {
		Weight::from_parts(197_900_000, 0)
			.saturating_add(RocksDbWeight::get().reads(24_u64))
			.saturating_add(RocksDbWeight::get().writes(20_u64))
	}
	fn set_weights() -> Weight {
		Weight::from_parts(15_540_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4111_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn add_stake() -> Weight {
		Weight::from_parts(340_800_000, 0)
			.saturating_add(RocksDbWeight::get().reads(27_u64))
			.saturating_add(RocksDbWeight::get().writes(15_u64))
	}
	fn serve_axon() -> Weight {
		Weight::from_parts(33_010_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn serve_prometheus() -> Weight {
		Weight::from_parts(29_760_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn burned_register() -> Weight {
		Weight::from_parts(354_200_000, 0)
			.saturating_add(RocksDbWeight::get().reads(47_u64))
			.saturating_add(RocksDbWeight::get().writes(39_u64))
	}
	fn root_register() -> Weight {
		Weight::from_parts(135_900_000, 0)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(16_u64))
	}
	fn register_network() -> Weight {
		Weight::from_parts(235_400_000, 0)
			.saturating_add(RocksDbWeight::get().reads(36_u64))
			.saturating_add(RocksDbWeight::get().writes(52_u64))
	}
	fn commit_weights() -> Weight {
		Weight::from_parts(67_770_000, 0)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn reveal_weights() -> Weight {
		Weight::from_parts(122_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn sudo_set_tx_childkey_take_rate_limit() -> Weight {
		Weight::from_parts(5_660_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn set_childkey_take() -> Weight {
		Weight::from_parts(66_450_000, 0)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn announce_coldkey_swap() -> Weight {
		Weight::from_parts(55_700_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn swap_coldkey_announced() -> Weight {
		Weight::from_parts(110_700_000, 0)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	fn swap_coldkey() -> Weight {
		Weight::from_parts(161_700_000, 0)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	fn dispute_coldkey_swap() -> Weight {
		Weight::from_parts(30_810_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn reset_coldkey_swap() -> Weight {
		Weight::from_parts(8_977_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn batch_reveal_weights() -> Weight {
		Weight::from_parts(412_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn recycle_alpha() -> Weight {
		Weight::from_parts(113_400_000, 0)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn burn_alpha() -> Weight {
		Weight::from_parts(112_200_000, 0)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn start_call() -> Weight {
		Weight::from_parts(29_780_000, 0)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn add_stake_limit() -> Weight {
		Weight::from_parts(402_900_000, 0)
			.saturating_add(RocksDbWeight::get().reads(27_u64))
			.saturating_add(RocksDbWeight::get().writes(15_u64))
	}
	fn move_stake() -> Weight {
		Weight::from_parts(164_300_000, 0)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	fn remove_stake_limit() -> Weight {
		Weight::from_parts(377_400_000, 0)
			.saturating_add(RocksDbWeight::get().reads(30_u64))
			.saturating_add(RocksDbWeight::get().writes(13_u64))
	}
	fn swap_stake_limit() -> Weight {
		Weight::from_parts(411_500_000, 0)
			.saturating_add(RocksDbWeight::get().reads(40_u64))
			.saturating_add(RocksDbWeight::get().writes(22_u64))
	}
	fn transfer_stake() -> Weight {
		Weight::from_parts(160_300_000, 0)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	fn swap_stake() -> Weight {
		Weight::from_parts(351_300_000, 0)
			.saturating_add(RocksDbWeight::get().reads(40_u64))
			.saturating_add(RocksDbWeight::get().writes(22_u64))
	}
	fn batch_commit_weights() -> Weight {
		Weight::from_parts(100_500_000, 0)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn batch_set_weights() -> Weight {
		Weight::from_parts(95_460_000, 0)
			.saturating_add(RocksDbWeight::get().reads(15_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn decrease_take() -> Weight {
		Weight::from_parts(30_020_000, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn increase_take() -> Weight {
		Weight::from_parts(36_710_000, 0)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn register_network_with_identity() -> Weight {
		Weight::from_parts(396_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(35_u64))
			.saturating_add(RocksDbWeight::get().writes(51_u64))
	}
	fn serve_axon_tls() -> Weight {
		Weight::from_parts(32_510_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn set_identity() -> Weight {
		Weight::from_parts(38_230_000, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn set_subnet_identity() -> Weight {
		Weight::from_parts(24_350_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn swap_hotkey() -> Weight {
		Weight::from_parts(275_300_000, 0)
			.saturating_add(RocksDbWeight::get().reads(57_u64))
			.saturating_add(RocksDbWeight::get().writes(39_u64))
	}
	fn try_associate_hotkey() -> Weight {
		Weight::from_parts(27_150_000, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn unstake_all() -> Weight {
		Weight::from_parts(28_830_000, 0)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
	}
	fn unstake_all_alpha() -> Weight {
		Weight::from_parts(358_500_000, 0)
			.saturating_add(RocksDbWeight::get().reads(44_u64))
			.saturating_add(RocksDbWeight::get().writes(24_u64))
	}
	fn remove_stake_full_limit() -> Weight {
		Weight::from_parts(395_300_000, 10142)
			.saturating_add(RocksDbWeight::get().reads(30_u64))
			.saturating_add(RocksDbWeight::get().writes(13_u64))
	}
	fn register_leased_network(_k: u32) -> Weight {
		Weight::from_parts(301_560_714, 10079)
			.saturating_add(Weight::from_parts(26_884_006, 0).saturating_mul(_k.into()))
			.saturating_add(RocksDbWeight::get().reads(41_u64))
			.saturating_add(RocksDbWeight::get().reads(2_u64.saturating_mul(_k.into())))
			.saturating_add(RocksDbWeight::get().writes(55_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64.saturating_mul(_k.into())))
			.saturating_add(Weight::from_parts(0, 2579).saturating_mul(_k.into()))
	}
	fn terminate_lease(_k: u32) -> Weight {
		Weight::from_parts(56_635_122, 6148)
			.saturating_add(Weight::from_parts(912_993, 0).saturating_mul(_k.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(_k.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(_k.into())))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(_k.into()))
	}
	fn update_symbol() -> Weight {
		Weight::from_parts(26_200_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn commit_timelocked_weights() -> Weight {
		Weight::from_parts(94_980_000, 0)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn set_coldkey_auto_stake_hotkey() -> Weight {
		Weight::from_parts(29_930_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn set_root_claim_type() -> Weight {
		Weight::from_parts(19_420_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn claim_root() -> Weight {
		Weight::from_parts(117_000_000, 7767)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn sudo_set_num_root_claims() -> Weight {
		Weight::from_parts(4_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn sudo_set_root_claim_threshold() -> Weight {
		Weight::from_parts(5_711_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn add_stake_burn() -> Weight {
		Weight::from_parts(368_000_000, 8556)
			.saturating_add(RocksDbWeight::get().reads(30_u64))
			.saturating_add(RocksDbWeight::get().writes(16_u64))
	}
}
