
//! Autogenerated weights for `pallet_crowdloan`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-04-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ubuntu-2404-noble-amd64-base`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("local")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/node-subtensor
// benchmark
// pallet
// --chain=local
// --wasm-execution=compiled
// --pallet=pallet-crowdloan
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/crowdloan/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs
// --allow-missing-host-functions

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_crowdloan`.
pub trait WeightInfo {
	fn create() -> Weight;
	fn contribute() -> Weight;
	fn withdraw() -> Weight;
	fn finalize() -> Weight;
	fn refund(k: u32, ) -> Weight;
	fn dissolve() -> Weight;
	fn update_min_contribution() -> Weight;
	fn update_end() -> Weight;
	fn update_cap() -> Weight;
}

/// Weights for `pallet_crowdloan` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::NextCrowdloanId` (r:1 w:1)
	/// Proof: `Crowdloan::NextCrowdloanId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:0 w:1)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Crowdloans` (r:0 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `156`
		//  Estimated: `6148`
		// Minimum execution time: 40_335_000 picoseconds.
		Weight::from_parts(41_647_000, 6148)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:1 w:1)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn contribute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `475`
		//  Estimated: `6148`
		// Minimum execution time: 43_691_000 picoseconds.
		Weight::from_parts(44_332_000, 6148)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:1 w:1)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `435`
		//  Estimated: `6148`
		// Minimum execution time: 40_235_000 picoseconds.
		Weight::from_parts(41_117_000, 6148)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::CurrentCrowdloanId` (r:0 w:1)
	/// Proof: `Crowdloan::CurrentCrowdloanId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `6148`
		// Minimum execution time: 40_636_000 picoseconds.
		Weight::from_parts(41_497_000, 6148)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:6 w:5)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:6 w:6)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `k` is `[3, 5]`.
	fn refund(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460 + k * (45 ±0)`
		//  Estimated: `3742 + k * (2579 ±0)`
		// Minimum execution time: 96_831_000 picoseconds.
		Weight::from_parts(23_219_468, 3742)
			// Standard Error: 128_696
			.saturating_add(Weight::from_parts(26_075_135, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(k.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2579).saturating_mul(k.into()))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn dissolve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3742`
		// Minimum execution time: 11_551_000 picoseconds.
		Weight::from_parts(12_092_000, 3742)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn update_min_contribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3742`
		// Minimum execution time: 8_667_000 picoseconds.
		Weight::from_parts(8_957_000, 3742)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn update_end() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3742`
		// Minimum execution time: 8_776_000 picoseconds.
		Weight::from_parts(9_067_000, 3742)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn update_cap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3742`
		// Minimum execution time: 8_546_000 picoseconds.
		Weight::from_parts(8_927_000, 3742)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::NextCrowdloanId` (r:1 w:1)
	/// Proof: `Crowdloan::NextCrowdloanId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:0 w:1)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Crowdloans` (r:0 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `156`
		//  Estimated: `6148`
		// Minimum execution time: 40_335_000 picoseconds.
		Weight::from_parts(41_647_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:1 w:1)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn contribute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `475`
		//  Estimated: `6148`
		// Minimum execution time: 43_691_000 picoseconds.
		Weight::from_parts(44_332_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:1 w:1)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `435`
		//  Estimated: `6148`
		// Minimum execution time: 40_235_000 picoseconds.
		Weight::from_parts(41_117_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::CurrentCrowdloanId` (r:0 w:1)
	/// Proof: `Crowdloan::CurrentCrowdloanId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `6148`
		// Minimum execution time: 40_636_000 picoseconds.
		Weight::from_parts(41_497_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `Crowdloan::Contributions` (r:6 w:5)
	/// Proof: `Crowdloan::Contributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:6 w:6)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `k` is `[3, 5]`.
	fn refund(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460 + k * (45 ±0)`
		//  Estimated: `3742 + k * (2579 ±0)`
		// Minimum execution time: 96_831_000 picoseconds.
		Weight::from_parts(23_219_468, 3742)
			// Standard Error: 128_696
			.saturating_add(Weight::from_parts(26_075_135, 0).saturating_mul(k.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(k.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2579).saturating_mul(k.into()))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn dissolve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3742`
		// Minimum execution time: 11_551_000 picoseconds.
		Weight::from_parts(12_092_000, 3742)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn update_min_contribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3742`
		// Minimum execution time: 8_667_000 picoseconds.
		Weight::from_parts(8_957_000, 3742)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn update_end() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3742`
		// Minimum execution time: 8_776_000 picoseconds.
		Weight::from_parts(9_067_000, 3742)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Crowdloan::Crowdloans` (r:1 w:1)
	/// Proof: `Crowdloan::Crowdloans` (`max_values`: None, `max_size`: Some(277), added: 2752, mode: `MaxEncodedLen`)
	fn update_cap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3742`
		// Minimum execution time: 8_546_000 picoseconds.
		Weight::from_parts(8_927_000, 3742)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}