// Weights for `pallet_crowdloan`.
//
// Stubbed entries were auto-generated by weight-stub.
// Re-generate with real values by running benchmarks:
//   ./scripts/benchmark_all.sh pallet_crowdloan

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_crowdloan`.
pub trait WeightInfo {
	fn create() -> Weight;
	fn contribute() -> Weight;
	fn withdraw() -> Weight;
	fn finalize() -> Weight;
	fn refund(k: u32) -> Weight;
	fn dissolve() -> Weight;
	fn update_min_contribution() -> Weight;
	fn update_end() -> Weight;
	fn update_cap() -> Weight;
}

/// Weights for `pallet_crowdloan` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create() -> Weight {
		Weight::from_parts(42_930_000, 6148)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	fn contribute() -> Weight {
		Weight::from_parts(44_192_000, 6148)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn withdraw() -> Weight {
		Weight::from_parts(40_907_000, 6148)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn finalize() -> Weight {
		Weight::from_parts(41_858_000, 6148)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn refund(_k: u32) -> Weight {
		Weight::from_parts(0, 2579)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	fn dissolve() -> Weight {
		Weight::from_parts(44_402_000, 6148)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn update_min_contribution() -> Weight {
		Weight::from_parts(9_137_000, 3743)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn update_end() -> Weight {
		Weight::from_parts(9_438_000, 3743)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn update_cap() -> Weight {
		Weight::from_parts(9_087_000, 3743)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create() -> Weight {
		Weight::from_parts(42_930_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	fn contribute() -> Weight {
		Weight::from_parts(44_192_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn withdraw() -> Weight {
		Weight::from_parts(40_907_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn finalize() -> Weight {
		Weight::from_parts(41_858_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn refund(_k: u32) -> Weight {
		Weight::from_parts(0, 2579)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	fn dissolve() -> Weight {
		Weight::from_parts(44_402_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn update_min_contribution() -> Weight {
		Weight::from_parts(9_137_000, 3743)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn update_end() -> Weight {
		Weight::from_parts(9_438_000, 3743)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn update_cap() -> Weight {
		Weight::from_parts(9_087_000, 3743)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
