
//! Autogenerated weights for `pallet_subtensor_proxy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-06-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm7b5n9`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/runner/work/subtensor/subtensor/target/production/node-subtensor
// benchmark
// pallet
// --runtime=/home/runner/work/subtensor/subtensor/target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet=pallet_subtensor_proxy
// --extrinsic=*
// --steps=50
// --repeat=20
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=/tmp/tmp.GehOD6jcDL
// --template=/home/runner/work/subtensor/subtensor/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_subtensor_proxy`.
pub trait WeightInfo {
	fn proxy(p: u32, ) -> Weight;
	fn proxy_announced(a: u32, p: u32, ) -> Weight;
	fn remove_announcement(a: u32, p: u32, ) -> Weight;
	fn reject_announcement(a: u32, p: u32, ) -> Weight;
	fn announce(a: u32, p: u32, ) -> Weight;
	fn add_proxy(p: u32, ) -> Weight;
	fn remove_proxy(p: u32, ) -> Weight;
	fn remove_proxies(p: u32, ) -> Weight;
	fn create_pure(p: u32, ) -> Weight;
	fn kill_pure(p: u32, ) -> Weight;
	fn poke_deposit() -> Weight;
	fn set_real_pays_fee(p: u32, ) -> Weight;
}

/// Weights for `pallet_subtensor_proxy` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `637 + p * (37 ±0)`
		//  Estimated: `4254 + p * (37 ±0)`
		// Minimum execution time: 26_079_000 picoseconds.
		Weight::from_parts(27_336_584, 4254)
			// Standard Error: 3_383
			.saturating_add(Weight::from_parts(56_015, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn proxy_announced(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615 + a * (68 ±0) + p * (37 ±0)`
		// Minimum execution time: 50_825_000 picoseconds.
		Weight::from_parts(51_505_523, 8615)
			// Standard Error: 1_493
			.saturating_add(Weight::from_parts(217_650, 0).saturating_mul(a.into()))
			// Standard Error: 5_982
			.saturating_add(Weight::from_parts(75_804, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 68).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn remove_announcement(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 25_087_000 picoseconds.
		Weight::from_parts(25_512_778, 8615)
			// Standard Error: 1_560
			.saturating_add(Weight::from_parts(205_376, 0).saturating_mul(a.into()))
			// Standard Error: 6_249
			.saturating_add(Weight::from_parts(946, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn reject_announcement(a: u32, _p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 24_987_000 picoseconds.
		Weight::from_parts(25_344_720, 8615)
			// Standard Error: 1_271
			.saturating_add(Weight::from_parts(209_750, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn announce(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 32_361_000 picoseconds.
		Weight::from_parts(32_404_265, 8615)
			// Standard Error: 1_307
			.saturating_add(Weight::from_parts(203_075, 0).saturating_mul(a.into()))
			// Standard Error: 5_236
			.saturating_add(Weight::from_parts(50_209, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn add_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 24_025_000 picoseconds.
		Weight::from_parts(24_694_480, 4254)
			// Standard Error: 2_742
			.saturating_add(Weight::from_parts(74_970, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 25_679_000 picoseconds.
		Weight::from_parts(26_636_199, 4254)
			// Standard Error: 2_510
			.saturating_add(Weight::from_parts(66_971, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxies(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 25_537_000 picoseconds.
		Weight::from_parts(26_548_572, 4254)
			// Standard Error: 3_027
			.saturating_add(Weight::from_parts(38_367, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn create_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `4254`
		// Minimum execution time: 25_678_000 picoseconds.
		Weight::from_parts(26_711_558, 4254)
			// Standard Error: 2_494
			.saturating_add(Weight::from_parts(23_627, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 18]`.
	fn kill_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `156 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 24_586_000 picoseconds.
		Weight::from_parts(25_686_861, 4254)
			// Standard Error: 2_382
			.saturating_add(Weight::from_parts(42_752, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	fn poke_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `8615`
		// Minimum execution time: 43_430_000 picoseconds.
		Weight::from_parts(44_663_000, 8615)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn set_real_pays_fee(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 13_345_000 picoseconds.
		Weight::from_parts(14_199_857, 4254)
			// Standard Error: 1_822
			.saturating_add(Weight::from_parts(35_497, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `637 + p * (37 ±0)`
		//  Estimated: `4254 + p * (37 ±0)`
		// Minimum execution time: 26_079_000 picoseconds.
		Weight::from_parts(27_336_584, 4254)
			// Standard Error: 3_383
			.saturating_add(Weight::from_parts(56_015, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn proxy_announced(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615 + a * (68 ±0) + p * (37 ±0)`
		// Minimum execution time: 50_825_000 picoseconds.
		Weight::from_parts(51_505_523, 8615)
			// Standard Error: 1_493
			.saturating_add(Weight::from_parts(217_650, 0).saturating_mul(a.into()))
			// Standard Error: 5_982
			.saturating_add(Weight::from_parts(75_804, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 68).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn remove_announcement(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 25_087_000 picoseconds.
		Weight::from_parts(25_512_778, 8615)
			// Standard Error: 1_560
			.saturating_add(Weight::from_parts(205_376, 0).saturating_mul(a.into()))
			// Standard Error: 6_249
			.saturating_add(Weight::from_parts(946, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn reject_announcement(a: u32, _p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 24_987_000 picoseconds.
		Weight::from_parts(25_344_720, 8615)
			// Standard Error: 1_271
			.saturating_add(Weight::from_parts(209_750, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn announce(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 32_361_000 picoseconds.
		Weight::from_parts(32_404_265, 8615)
			// Standard Error: 1_307
			.saturating_add(Weight::from_parts(203_075, 0).saturating_mul(a.into()))
			// Standard Error: 5_236
			.saturating_add(Weight::from_parts(50_209, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn add_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 24_025_000 picoseconds.
		Weight::from_parts(24_694_480, 4254)
			// Standard Error: 2_742
			.saturating_add(Weight::from_parts(74_970, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 25_679_000 picoseconds.
		Weight::from_parts(26_636_199, 4254)
			// Standard Error: 2_510
			.saturating_add(Weight::from_parts(66_971, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxies(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 25_537_000 picoseconds.
		Weight::from_parts(26_548_572, 4254)
			// Standard Error: 3_027
			.saturating_add(Weight::from_parts(38_367, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn create_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `4254`
		// Minimum execution time: 25_678_000 picoseconds.
		Weight::from_parts(26_711_558, 4254)
			// Standard Error: 2_494
			.saturating_add(Weight::from_parts(23_627, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 18]`.
	fn kill_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `156 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 24_586_000 picoseconds.
		Weight::from_parts(25_686_861, 4254)
			// Standard Error: 2_382
			.saturating_add(Weight::from_parts(42_752, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	fn poke_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `8615`
		// Minimum execution time: 43_430_000 picoseconds.
		Weight::from_parts(44_663_000, 8615)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn set_real_pays_fee(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 13_345_000 picoseconds.
		Weight::from_parts(14_199_857, 4254)
			// Standard Error: 1_822
			.saturating_add(Weight::from_parts(35_497, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
