
//! Autogenerated weights for `governance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-05-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervmg397c`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/runner/work/subtensor/subtensor/target/production/node-subtensor
// benchmark
// pallet
// --runtime=/home/runner/work/subtensor/subtensor/target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet=governance
// --extrinsic=*
// --steps=50
// --repeat=20
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=/tmp/tmp.JF1LCW5Q9K
// --template=/home/runner/work/subtensor/subtensor/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `governance`.
pub trait WeightInfo {
	fn stake_ema_provider_step() -> Weight;
	fn rotate_economic() -> Weight;
	fn rotate_building() -> Weight;
}

/// Weights for `governance` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SubtensorModule::NetworksAdded` (r:11 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::OwnedHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::OwnedHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:2048 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:7 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn stake_ema_provider_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `48134`
		//  Estimated: `5117924`
		// Minimum execution time: 6_809_228_000 picoseconds.
		Weight::from_parts(6_912_642_000, 5117924)
			.saturating_add(T::DbWeight::get().reads(2067_u64))
	}
	/// Storage: `MultiCollective::Members` (r:2 w:1)
	/// Proof: `MultiCollective::Members` (`max_values`: None, `max_size`: Some(2067), added: 4542, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::RootRegisteredEma` (r:64 w:0)
	/// Proof: `SubtensorModule::RootRegisteredEma` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn rotate_economic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7996`
		//  Estimated: `167386`
		// Minimum execution time: 280_504_000 picoseconds.
		Weight::from_parts(284_522_000, 167386)
			.saturating_add(T::DbWeight::get().reads(66_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:131 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworkRegisteredAt` (r:130 w:0)
	/// Proof: `SubtensorModule::NetworkRegisteredAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:130 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetOwner` (r:130 w:0)
	/// Proof: `SubtensorModule::SubnetOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiCollective::Members` (r:1 w:1)
	/// Proof: `MultiCollective::Members` (`max_values`: None, `max_size`: Some(2067), added: 4542, mode: `MaxEncodedLen`)
	fn rotate_building() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11112`
		//  Estimated: `336327`
		// Minimum execution time: 1_106_639_000 picoseconds.
		Weight::from_parts(1_118_871_000, 336327)
			.saturating_add(T::DbWeight::get().reads(522_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `SubtensorModule::NetworksAdded` (r:11 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::OwnedHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::OwnedHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:2048 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:7 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn stake_ema_provider_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `48134`
		//  Estimated: `5117924`
		// Minimum execution time: 6_809_228_000 picoseconds.
		Weight::from_parts(6_912_642_000, 5117924)
			.saturating_add(ParityDbWeight::get().reads(2067_u64))
	}
	/// Storage: `MultiCollective::Members` (r:2 w:1)
	/// Proof: `MultiCollective::Members` (`max_values`: None, `max_size`: Some(2067), added: 4542, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::RootRegisteredEma` (r:64 w:0)
	/// Proof: `SubtensorModule::RootRegisteredEma` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn rotate_economic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7996`
		//  Estimated: `167386`
		// Minimum execution time: 280_504_000 picoseconds.
		Weight::from_parts(284_522_000, 167386)
			.saturating_add(ParityDbWeight::get().reads(66_u64))
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:131 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworkRegisteredAt` (r:130 w:0)
	/// Proof: `SubtensorModule::NetworkRegisteredAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:130 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetOwner` (r:130 w:0)
	/// Proof: `SubtensorModule::SubnetOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiCollective::Members` (r:1 w:1)
	/// Proof: `MultiCollective::Members` (`max_values`: None, `max_size`: Some(2067), added: 4542, mode: `MaxEncodedLen`)
	fn rotate_building() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11112`
		//  Estimated: `336327`
		// Minimum execution time: 1_106_639_000 picoseconds.
		Weight::from_parts(1_118_871_000, 336327)
			.saturating_add(ParityDbWeight::get().reads(522_u64))
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
}
