
//! Autogenerated weights for `pallet_admin_utils`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-05-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervmeorf1`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/runner/work/subtensor/subtensor/target/production/node-subtensor
// benchmark
// pallet
// --runtime=/home/runner/work/subtensor/subtensor/target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet=pallet_admin_utils
// --extrinsic=*
// --steps=50
// --repeat=20
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=/tmp/tmp.bzwIs210x3
// --template=/home/runner/work/subtensor/subtensor/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_admin_utils`.
pub trait WeightInfo {
	fn swap_authorities(a: u32, ) -> Weight;
	fn schedule_grandpa_change(a: u32, ) -> Weight;
	fn sudo_set_default_take() -> Weight;
	fn sudo_set_serving_rate_limit() -> Weight;
	fn sudo_set_max_difficulty() -> Weight;
	fn sudo_set_min_difficulty() -> Weight;
	fn sudo_set_weights_set_rate_limit() -> Weight;
	fn sudo_set_weights_version_key() -> Weight;
	fn sudo_set_bonds_moving_average() -> Weight;
	fn sudo_set_bonds_penalty() -> Weight;
	fn sudo_set_max_allowed_validators() -> Weight;
	fn sudo_set_difficulty() -> Weight;
	fn sudo_set_adjustment_interval() -> Weight;
	fn sudo_set_target_registrations_per_interval() -> Weight;
	fn sudo_set_activity_cutoff() -> Weight;
	fn sudo_set_rho() -> Weight;
	fn sudo_set_kappa() -> Weight;
	fn sudo_set_min_allowed_uids() -> Weight;
	fn sudo_set_max_allowed_uids() -> Weight;
	fn sudo_set_min_allowed_weights() -> Weight;
	fn sudo_set_immunity_period() -> Weight;
	fn sudo_set_max_registrations_per_block() -> Weight;
	fn sudo_set_max_burn() -> Weight;
	fn sudo_set_min_burn() -> Weight;
	fn sudo_set_network_registration_allowed() -> Weight;
	fn sudo_set_tempo() -> Weight;
	fn sudo_set_commit_reveal_weights_interval() -> Weight;
	fn sudo_set_commit_reveal_weights_enabled() -> Weight;
	fn sudo_set_commit_reveal_version() -> Weight;
	fn sudo_set_tx_rate_limit() -> Weight;
	fn sudo_set_total_issuance() -> Weight;
	fn sudo_set_rao_recycled() -> Weight;
	fn sudo_set_stake_threshold() -> Weight;
	fn sudo_set_nominator_min_required_stake() -> Weight;
	fn sudo_set_tx_delegate_take_rate_limit() -> Weight;
	fn sudo_set_min_delegate_take() -> Weight;
	fn sudo_set_liquid_alpha_enabled() -> Weight;
	fn sudo_set_alpha_values() -> Weight;
	fn sudo_set_coldkey_swap_announcement_delay() -> Weight;
	fn sudo_set_coldkey_swap_reannouncement_delay() -> Weight;
	fn sudo_set_dissolve_network_schedule_duration() -> Weight;
	fn sudo_set_toggle_transfer() -> Weight;
	fn sudo_toggle_evm_precompile() -> Weight;
	fn sudo_set_subnet_moving_alpha() -> Weight;
	fn sudo_set_ema_price_halving_period() -> Weight;
	fn sudo_set_alpha_sigmoid_steepness() -> Weight;
	fn sudo_set_yuma3_enabled() -> Weight;
	fn sudo_set_bonds_reset_enabled() -> Weight;
	fn sudo_set_sn_owner_hotkey() -> Weight;
	fn sudo_set_subtoken_enabled() -> Weight;
	fn sudo_set_admin_freeze_window() -> Weight;
	fn sudo_set_owner_hparam_rate_limit() -> Weight;
	fn sudo_set_owner_immune_neuron_limit() -> Weight;
	fn sudo_trim_to_max_allowed_uids() -> Weight;
	fn sudo_set_min_non_immune_uids() -> Weight;
}

/// Weights for `pallet_admin_utils` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Aura::Authorities` (r:0 w:1)
	/// Proof: `Aura::Authorities` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 32]`.
	fn swap_authorities(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_107_000 picoseconds.
		Weight::from_parts(4_669_529, 0)
			// Standard Error: 694
			.saturating_add(Weight::from_parts(28_939, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Grandpa::PendingChange` (r:1 w:1)
	/// Proof: `Grandpa::PendingChange` (`max_values`: Some(1), `max_size`: Some(1294), added: 1789, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 32]`.
	fn schedule_grandpa_change(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `2779`
		// Minimum execution time: 7_354_000 picoseconds.
		Weight::from_parts(7_977_975, 2779)
			// Standard Error: 897
			.saturating_add(Weight::from_parts(19_089, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::MaxDelegateTake` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxDelegateTake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_default_take() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_460_000 picoseconds.
		Weight::from_parts(5_660_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ServingRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::ServingRateLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_serving_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `627`
		//  Estimated: `4092`
		// Minimum execution time: 21_369_000 picoseconds.
		Weight::from_parts(21_761_000, 4092)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxDifficulty` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxDifficulty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_difficulty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_941_000 picoseconds.
		Weight::from_parts(27_481_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinDifficulty` (r:0 w:1)
	/// Proof: `SubtensorModule::MinDifficulty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_difficulty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_770_000 picoseconds.
		Weight::from_parts(28_022_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::WeightsSetRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::WeightsSetRateLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_weights_set_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_942_000 picoseconds.
		Weight::from_parts(17_423_000, 4074)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::WeightsVersionKey` (r:0 w:1)
	/// Proof: `SubtensorModule::WeightsVersionKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_weights_version_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 27_061_000 picoseconds.
		Weight::from_parts(27_863_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::BondsMovingAverage` (r:0 w:1)
	/// Proof: `SubtensorModule::BondsMovingAverage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_bonds_moving_average() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_761_000 picoseconds.
		Weight::from_parts(27_592_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::BondsPenalty` (r:0 w:1)
	/// Proof: `SubtensorModule::BondsPenalty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_bonds_penalty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_731_000 picoseconds.
		Weight::from_parts(27_391_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedValidators` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxAllowedValidators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_allowed_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 28_133_000 picoseconds.
		Weight::from_parts(29_195_000, 4225)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Difficulty` (r:0 w:1)
	/// Proof: `SubtensorModule::Difficulty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_difficulty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_921_000 picoseconds.
		Weight::from_parts(27_752_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdjustmentInterval` (r:0 w:1)
	/// Proof: `SubtensorModule::AdjustmentInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_adjustment_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_871_000 picoseconds.
		Weight::from_parts(17_273_000, 4074)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TargetRegistrationsPerInterval` (r:0 w:1)
	/// Proof: `SubtensorModule::TargetRegistrationsPerInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_target_registrations_per_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_489_000 picoseconds.
		Weight::from_parts(27_502_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinActivityCutoff` (r:1 w:0)
	/// Proof: `SubtensorModule::MinActivityCutoff` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ActivityCutoff` (r:0 w:1)
	/// Proof: `SubtensorModule::ActivityCutoff` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_activity_cutoff() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `4287`
		// Minimum execution time: 29_044_000 picoseconds.
		Weight::from_parts(29_806_000, 4287)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Rho` (r:0 w:1)
	/// Proof: `SubtensorModule::Rho` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_rho() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 24_015_000 picoseconds.
		Weight::from_parts(24_687_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Kappa` (r:0 w:1)
	/// Proof: `SubtensorModule::Kappa` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_kappa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_671_000 picoseconds.
		Weight::from_parts(17_192_000, 4074)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetworkN` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetworkN` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedUids` (r:0 w:1)
	/// Proof: `SubtensorModule::MinAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_allowed_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 30_287_000 picoseconds.
		Weight::from_parts(30_909_000, 4225)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MinAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetworkN` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetworkN` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MechanismCountCurrent` (r:1 w:0)
	/// Proof: `SubtensorModule::MechanismCountCurrent` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_allowed_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `795`
		//  Estimated: `4260`
		// Minimum execution time: 33_323_000 picoseconds.
		Weight::from_parts(34_174_000, 4260)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedWeights` (r:0 w:1)
	/// Proof: `SubtensorModule::MinAllowedWeights` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_allowed_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_830_000 picoseconds.
		Weight::from_parts(27_822_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ImmunityPeriod` (r:0 w:1)
	/// Proof: `SubtensorModule::ImmunityPeriod` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_immunity_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_620_000 picoseconds.
		Weight::from_parts(27_331_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxRegistrationsPerBlock` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxRegistrationsPerBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_registrations_per_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_721_000 picoseconds.
		Weight::from_parts(27_672_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinBurn` (r:1 w:0)
	/// Proof: `SubtensorModule::MinBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxBurn` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `787`
		//  Estimated: `4252`
		// Minimum execution time: 30_026_000 picoseconds.
		Weight::from_parts(30_938_000, 4252)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxBurn` (r:1 w:0)
	/// Proof: `SubtensorModule::MaxBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinBurn` (r:0 w:1)
	/// Proof: `SubtensorModule::MinBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `762`
		//  Estimated: `4227`
		// Minimum execution time: 29_987_000 picoseconds.
		Weight::from_parts(31_009_000, 4227)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworkRegistrationAllowed` (r:0 w:1)
	/// Proof: `SubtensorModule::NetworkRegistrationAllowed` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_network_registration_allowed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_712_000 picoseconds.
		Weight::from_parts(7_083_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:1)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_tempo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_389_000 picoseconds.
		Weight::from_parts(27_351_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::RevealPeriodEpochs` (r:0 w:1)
	/// Proof: `SubtensorModule::RevealPeriodEpochs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_commit_reveal_weights_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 27_111_000 picoseconds.
		Weight::from_parts(27_852_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::CommitRevealWeightsEnabled` (r:0 w:1)
	/// Proof: `SubtensorModule::CommitRevealWeightsEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_commit_reveal_weights_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_490_000 picoseconds.
		Weight::from_parts(27_582_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::CommitRevealWeightsVersion` (r:0 w:1)
	/// Proof: `SubtensorModule::CommitRevealWeightsVersion` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_commit_reveal_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_071_000 picoseconds.
		Weight::from_parts(6_272_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::TxRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_tx_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_330_000 picoseconds.
		Weight::from_parts(5_651_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn sudo_set_total_issuance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_841_000 picoseconds.
		Weight::from_parts(6_101_000, 0)
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::RAORecycledForRegistration` (r:0 w:1)
	/// Proof: `SubtensorModule::RAORecycledForRegistration` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_rao_recycled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_622_000 picoseconds.
		Weight::from_parts(17_112_000, 4074)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::StakeThreshold` (r:0 w:1)
	/// Proof: `SubtensorModule::StakeThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_stake_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_490_000 picoseconds.
		Weight::from_parts(5_721_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NominatorMinRequiredStake` (r:1 w:1)
	/// Proof: `SubtensorModule::NominatorMinRequiredStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:2 w:0)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Owner` (r:1 w:0)
	/// Proof: `SubtensorModule::Owner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_nominator_min_required_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `912`
		//  Estimated: `6852`
		// Minimum execution time: 28_945_000 picoseconds.
		Weight::from_parts(29_506_000, 6852)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::TxDelegateTakeRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::TxDelegateTakeRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_tx_delegate_take_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_360_000 picoseconds.
		Weight::from_parts(5_631_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::MinDelegateTake` (r:0 w:1)
	/// Proof: `SubtensorModule::MinDelegateTake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_min_delegate_take() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_420_000 picoseconds.
		Weight::from_parts(5_661_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LiquidAlphaOn` (r:0 w:1)
	/// Proof: `SubtensorModule::LiquidAlphaOn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_liquid_alpha_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 18_154_000 picoseconds.
		Weight::from_parts(18_965_000, 4122)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LiquidAlphaOn` (r:1 w:0)
	/// Proof: `SubtensorModule::LiquidAlphaOn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaValues` (r:0 w:1)
	/// Proof: `SubtensorModule::AlphaValues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_alpha_values() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `804`
		//  Estimated: `4269`
		// Minimum execution time: 26_549_000 picoseconds.
		Weight::from_parts(27_282_000, 4269)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncementDelay` (r:0 w:1)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncementDelay` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_coldkey_swap_announcement_delay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_470_000 picoseconds.
		Weight::from_parts(5_761_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::ColdkeySwapReannouncementDelay` (r:0 w:1)
	/// Proof: `SubtensorModule::ColdkeySwapReannouncementDelay` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_coldkey_swap_reannouncement_delay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_320_000 picoseconds.
		Weight::from_parts(5_571_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::DissolveNetworkScheduleDuration` (r:0 w:1)
	/// Proof: `SubtensorModule::DissolveNetworkScheduleDuration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_dissolve_network_schedule_duration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_340_000 picoseconds.
		Weight::from_parts(5_651_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TransferToggle` (r:0 w:1)
	/// Proof: `SubtensorModule::TransferToggle` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_toggle_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 20_618_000 picoseconds.
		Weight::from_parts(21_260_000, 4122)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AdminUtils::PrecompileEnable` (r:1 w:0)
	/// Proof: `AdminUtils::PrecompileEnable` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_toggle_evm_precompile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3507`
		// Minimum execution time: 6_071_000 picoseconds.
		Weight::from_parts(6_342_000, 3507)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `SubtensorModule::SubnetMovingAlpha` (r:0 w:1)
	/// Proof: `SubtensorModule::SubnetMovingAlpha` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_subnet_moving_alpha() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_765_000 picoseconds.
		Weight::from_parts(2_945_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::EMAPriceHalvingBlocks` (r:0 w:1)
	/// Proof: `SubtensorModule::EMAPriceHalvingBlocks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_ema_price_halving_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_008_000 picoseconds.
		Weight::from_parts(4_188_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaSigmoidSteepness` (r:0 w:1)
	/// Proof: `SubtensorModule::AlphaSigmoidSteepness` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_alpha_sigmoid_steepness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 23_985_000 picoseconds.
		Weight::from_parts(24_706_000, 4225)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Yuma3On` (r:0 w:1)
	/// Proof: `SubtensorModule::Yuma3On` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_yuma3_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 20_799_000 picoseconds.
		Weight::from_parts(21_410_000, 4122)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::BondsResetOn` (r:0 w:1)
	/// Proof: `SubtensorModule::BondsResetOn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_bonds_reset_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 22_873_000 picoseconds.
		Weight::from_parts(23_705_000, 4122)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LastRateLimitedBlock` (r:1 w:1)
	/// Proof: `SubtensorModule::LastRateLimitedBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetOwnerHotkey` (r:0 w:1)
	/// Proof: `SubtensorModule::SubnetOwnerHotkey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_sn_owner_hotkey() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `702`
		//  Estimated: `4167`
		// Minimum execution time: 25_538_000 picoseconds.
		Weight::from_parts(26_420_000, 4167)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:0 w:1)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_subtoken_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 17_713_000 picoseconds.
		Weight::from_parts(18_284_000, 4122)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:0 w:1)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_admin_freeze_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_300_000 picoseconds.
		Weight::from_parts(5_611_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::OwnerHyperparamRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::OwnerHyperparamRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_owner_hparam_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_390_000 picoseconds.
		Weight::from_parts(5_651_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ImmuneOwnerUidsLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::ImmuneOwnerUidsLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_owner_immune_neuron_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 17_874_000 picoseconds.
		Weight::from_parts(18_214_000, 4122)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MinAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:1 w:1)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetworkN` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetworkN` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_trim_to_max_allowed_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 28_153_000 picoseconds.
		Weight::from_parts(28_744_000, 4225)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::MinNonImmuneUids` (r:0 w:1)
	/// Proof: `SubtensorModule::MinNonImmuneUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_non_immune_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_803_000 picoseconds.
		Weight::from_parts(7_233_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Aura::Authorities` (r:0 w:1)
	/// Proof: `Aura::Authorities` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 32]`.
	fn swap_authorities(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_107_000 picoseconds.
		Weight::from_parts(4_669_529, 0)
			// Standard Error: 694
			.saturating_add(Weight::from_parts(28_939, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Grandpa::PendingChange` (r:1 w:1)
	/// Proof: `Grandpa::PendingChange` (`max_values`: Some(1), `max_size`: Some(1294), added: 1789, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 32]`.
	fn schedule_grandpa_change(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `2779`
		// Minimum execution time: 7_354_000 picoseconds.
		Weight::from_parts(7_977_975, 2779)
			// Standard Error: 897
			.saturating_add(Weight::from_parts(19_089, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::MaxDelegateTake` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxDelegateTake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_default_take() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_460_000 picoseconds.
		Weight::from_parts(5_660_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ServingRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::ServingRateLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_serving_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `627`
		//  Estimated: `4092`
		// Minimum execution time: 21_369_000 picoseconds.
		Weight::from_parts(21_761_000, 4092)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxDifficulty` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxDifficulty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_difficulty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_941_000 picoseconds.
		Weight::from_parts(27_481_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinDifficulty` (r:0 w:1)
	/// Proof: `SubtensorModule::MinDifficulty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_difficulty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_770_000 picoseconds.
		Weight::from_parts(28_022_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::WeightsSetRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::WeightsSetRateLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_weights_set_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_942_000 picoseconds.
		Weight::from_parts(17_423_000, 4074)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::WeightsVersionKey` (r:0 w:1)
	/// Proof: `SubtensorModule::WeightsVersionKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_weights_version_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 27_061_000 picoseconds.
		Weight::from_parts(27_863_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::BondsMovingAverage` (r:0 w:1)
	/// Proof: `SubtensorModule::BondsMovingAverage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_bonds_moving_average() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_761_000 picoseconds.
		Weight::from_parts(27_592_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::BondsPenalty` (r:0 w:1)
	/// Proof: `SubtensorModule::BondsPenalty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_bonds_penalty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_731_000 picoseconds.
		Weight::from_parts(27_391_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedValidators` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxAllowedValidators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_allowed_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 28_133_000 picoseconds.
		Weight::from_parts(29_195_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Difficulty` (r:0 w:1)
	/// Proof: `SubtensorModule::Difficulty` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_difficulty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_921_000 picoseconds.
		Weight::from_parts(27_752_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdjustmentInterval` (r:0 w:1)
	/// Proof: `SubtensorModule::AdjustmentInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_adjustment_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_871_000 picoseconds.
		Weight::from_parts(17_273_000, 4074)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TargetRegistrationsPerInterval` (r:0 w:1)
	/// Proof: `SubtensorModule::TargetRegistrationsPerInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_target_registrations_per_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_489_000 picoseconds.
		Weight::from_parts(27_502_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinActivityCutoff` (r:1 w:0)
	/// Proof: `SubtensorModule::MinActivityCutoff` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ActivityCutoff` (r:0 w:1)
	/// Proof: `SubtensorModule::ActivityCutoff` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_activity_cutoff() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `4287`
		// Minimum execution time: 29_044_000 picoseconds.
		Weight::from_parts(29_806_000, 4287)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Rho` (r:0 w:1)
	/// Proof: `SubtensorModule::Rho` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_rho() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 24_015_000 picoseconds.
		Weight::from_parts(24_687_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Kappa` (r:0 w:1)
	/// Proof: `SubtensorModule::Kappa` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_kappa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_671_000 picoseconds.
		Weight::from_parts(17_192_000, 4074)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetworkN` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetworkN` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedUids` (r:0 w:1)
	/// Proof: `SubtensorModule::MinAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_allowed_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 30_287_000 picoseconds.
		Weight::from_parts(30_909_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MinAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetworkN` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetworkN` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MechanismCountCurrent` (r:1 w:0)
	/// Proof: `SubtensorModule::MechanismCountCurrent` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_allowed_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `795`
		//  Estimated: `4260`
		// Minimum execution time: 33_323_000 picoseconds.
		Weight::from_parts(34_174_000, 4260)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedWeights` (r:0 w:1)
	/// Proof: `SubtensorModule::MinAllowedWeights` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_allowed_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_830_000 picoseconds.
		Weight::from_parts(27_822_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ImmunityPeriod` (r:0 w:1)
	/// Proof: `SubtensorModule::ImmunityPeriod` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_immunity_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_620_000 picoseconds.
		Weight::from_parts(27_331_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxRegistrationsPerBlock` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxRegistrationsPerBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_registrations_per_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_721_000 picoseconds.
		Weight::from_parts(27_672_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinBurn` (r:1 w:0)
	/// Proof: `SubtensorModule::MinBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxBurn` (r:0 w:1)
	/// Proof: `SubtensorModule::MaxBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_max_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `787`
		//  Estimated: `4252`
		// Minimum execution time: 30_026_000 picoseconds.
		Weight::from_parts(30_938_000, 4252)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxBurn` (r:1 w:0)
	/// Proof: `SubtensorModule::MaxBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinBurn` (r:0 w:1)
	/// Proof: `SubtensorModule::MinBurn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `762`
		//  Estimated: `4227`
		// Minimum execution time: 29_987_000 picoseconds.
		Weight::from_parts(31_009_000, 4227)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworkRegistrationAllowed` (r:0 w:1)
	/// Proof: `SubtensorModule::NetworkRegistrationAllowed` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_network_registration_allowed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_712_000 picoseconds.
		Weight::from_parts(7_083_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:1)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_tempo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_389_000 picoseconds.
		Weight::from_parts(27_351_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::RevealPeriodEpochs` (r:0 w:1)
	/// Proof: `SubtensorModule::RevealPeriodEpochs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_commit_reveal_weights_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 27_111_000 picoseconds.
		Weight::from_parts(27_852_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::CommitRevealWeightsEnabled` (r:0 w:1)
	/// Proof: `SubtensorModule::CommitRevealWeightsEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_commit_reveal_weights_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 26_490_000 picoseconds.
		Weight::from_parts(27_582_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::CommitRevealWeightsVersion` (r:0 w:1)
	/// Proof: `SubtensorModule::CommitRevealWeightsVersion` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_commit_reveal_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_071_000 picoseconds.
		Weight::from_parts(6_272_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::TxRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::TxRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_tx_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_330_000 picoseconds.
		Weight::from_parts(5_651_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn sudo_set_total_issuance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_841_000 picoseconds.
		Weight::from_parts(6_101_000, 0)
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::RAORecycledForRegistration` (r:0 w:1)
	/// Proof: `SubtensorModule::RAORecycledForRegistration` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_rao_recycled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `4074`
		// Minimum execution time: 16_622_000 picoseconds.
		Weight::from_parts(17_112_000, 4074)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::StakeThreshold` (r:0 w:1)
	/// Proof: `SubtensorModule::StakeThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_stake_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_490_000 picoseconds.
		Weight::from_parts(5_721_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NominatorMinRequiredStake` (r:1 w:1)
	/// Proof: `SubtensorModule::NominatorMinRequiredStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:2 w:0)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Owner` (r:1 w:0)
	/// Proof: `SubtensorModule::Owner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_nominator_min_required_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `912`
		//  Estimated: `6852`
		// Minimum execution time: 28_945_000 picoseconds.
		Weight::from_parts(29_506_000, 6852)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::TxDelegateTakeRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::TxDelegateTakeRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_tx_delegate_take_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_360_000 picoseconds.
		Weight::from_parts(5_631_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::MinDelegateTake` (r:0 w:1)
	/// Proof: `SubtensorModule::MinDelegateTake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_min_delegate_take() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_420_000 picoseconds.
		Weight::from_parts(5_661_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LiquidAlphaOn` (r:0 w:1)
	/// Proof: `SubtensorModule::LiquidAlphaOn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_liquid_alpha_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 18_154_000 picoseconds.
		Weight::from_parts(18_965_000, 4122)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LiquidAlphaOn` (r:1 w:0)
	/// Proof: `SubtensorModule::LiquidAlphaOn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaValues` (r:0 w:1)
	/// Proof: `SubtensorModule::AlphaValues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_alpha_values() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `804`
		//  Estimated: `4269`
		// Minimum execution time: 26_549_000 picoseconds.
		Weight::from_parts(27_282_000, 4269)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncementDelay` (r:0 w:1)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncementDelay` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_coldkey_swap_announcement_delay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_470_000 picoseconds.
		Weight::from_parts(5_761_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::ColdkeySwapReannouncementDelay` (r:0 w:1)
	/// Proof: `SubtensorModule::ColdkeySwapReannouncementDelay` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_coldkey_swap_reannouncement_delay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_320_000 picoseconds.
		Weight::from_parts(5_571_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::DissolveNetworkScheduleDuration` (r:0 w:1)
	/// Proof: `SubtensorModule::DissolveNetworkScheduleDuration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_dissolve_network_schedule_duration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_340_000 picoseconds.
		Weight::from_parts(5_651_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TransferToggle` (r:0 w:1)
	/// Proof: `SubtensorModule::TransferToggle` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_toggle_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 20_618_000 picoseconds.
		Weight::from_parts(21_260_000, 4122)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AdminUtils::PrecompileEnable` (r:1 w:0)
	/// Proof: `AdminUtils::PrecompileEnable` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_toggle_evm_precompile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3507`
		// Minimum execution time: 6_071_000 picoseconds.
		Weight::from_parts(6_342_000, 3507)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `SubtensorModule::SubnetMovingAlpha` (r:0 w:1)
	/// Proof: `SubtensorModule::SubnetMovingAlpha` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_subnet_moving_alpha() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_765_000 picoseconds.
		Weight::from_parts(2_945_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::EMAPriceHalvingBlocks` (r:0 w:1)
	/// Proof: `SubtensorModule::EMAPriceHalvingBlocks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_ema_price_halving_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_008_000 picoseconds.
		Weight::from_parts(4_188_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaSigmoidSteepness` (r:0 w:1)
	/// Proof: `SubtensorModule::AlphaSigmoidSteepness` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_alpha_sigmoid_steepness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 23_985_000 picoseconds.
		Weight::from_parts(24_706_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Yuma3On` (r:0 w:1)
	/// Proof: `SubtensorModule::Yuma3On` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_yuma3_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 20_799_000 picoseconds.
		Weight::from_parts(21_410_000, 4122)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::BondsResetOn` (r:0 w:1)
	/// Proof: `SubtensorModule::BondsResetOn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_bonds_reset_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 22_873_000 picoseconds.
		Weight::from_parts(23_705_000, 4122)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::LastRateLimitedBlock` (r:1 w:1)
	/// Proof: `SubtensorModule::LastRateLimitedBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetOwnerHotkey` (r:0 w:1)
	/// Proof: `SubtensorModule::SubnetOwnerHotkey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_sn_owner_hotkey() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `702`
		//  Estimated: `4167`
		// Minimum execution time: 25_538_000 picoseconds.
		Weight::from_parts(26_420_000, 4167)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:0 w:1)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_subtoken_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 17_713_000 picoseconds.
		Weight::from_parts(18_284_000, 4122)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:0 w:1)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_admin_freeze_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_300_000 picoseconds.
		Weight::from_parts(5_611_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::OwnerHyperparamRateLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::OwnerHyperparamRateLimit` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn sudo_set_owner_hparam_rate_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_390_000 picoseconds.
		Weight::from_parts(5_651_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::ImmuneOwnerUidsLimit` (r:0 w:1)
	/// Proof: `SubtensorModule::ImmuneOwnerUidsLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_owner_immune_neuron_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 17_874_000 picoseconds.
		Weight::from_parts(18_214_000, 4122)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::Tempo` (r:1 w:0)
	/// Proof: `SubtensorModule::Tempo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AdminFreezeWindow` (r:1 w:0)
	/// Proof: `SubtensorModule::AdminFreezeWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MinAllowedUids` (r:1 w:0)
	/// Proof: `SubtensorModule::MinAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::MaxAllowedUids` (r:1 w:1)
	/// Proof: `SubtensorModule::MaxAllowedUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetworkN` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetworkN` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_trim_to_max_allowed_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `4225`
		// Minimum execution time: 28_153_000 picoseconds.
		Weight::from_parts(28_744_000, 4225)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SubtensorModule::MinNonImmuneUids` (r:0 w:1)
	/// Proof: `SubtensorModule::MinNonImmuneUids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo_set_min_non_immune_uids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_803_000 picoseconds.
		Weight::from_parts(7_233_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
