name: E2E Bittensor Tests

concurrency:
  group: e2e-bittensor-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  ## Allow running workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      verbose:
        description: "Output more information when triggered manually"
        required: false
        default: ""

env:
  CARGO_TERM_COLOR: always
  VERBOSE: ${{ github.events.input.verbose }}

jobs:
  run:
    runs-on: SubtensorCI
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Clone bittensor repo
        run: git clone https://github.com/opentensor/bittensor.git

      - name: Setup bittensor repo
        working-directory: ${{ github.workspace }}/bittensor
        run: |
          git checkout fix-no-sudo-set
          python3 -m pip install -e .
          python3 -m pip install torch
          python3 -m pip install pytest
          python3 -m pip install -r requirements/dev.txt

      - name: Run tests
        working-directory: ${{ github.workspace }}/bittensor
        run: |
          pwd
          ls
          LOCALNET_SH_PATH="${{ github.workspace }}/scripts/localnet.sh" pytest tests/e2e_tests/ -s
