name: E2E Bittensor Tests

concurrency:
  group: e2e-bittensor-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main, devnet-ready, devnet, testnet, finney]

  pull_request:

  ## Allow running workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      verbose:
        description: "Output more information when triggered manually"
        required: false
        default: ""

env:
  CARGO_TERM_COLOR: always
  VERBOSE: ${{ github.events.input.verbose }}

jobs:
  run:
    runs-on: SubtensorCI
    strategy:
      matrix:
        rust-branch:
          - nightly-2024-03-05
        rust-target:
          - x86_64-unknown-linux-gnu
          # - x86_64-apple-darwin
        os:
          - ubuntu-latest
          # - macos-latest
        include:
          - os: ubuntu-latest
          # - os: macos-latest
    env:
      RELEASE_NAME: development
      RUSTV: ${{ matrix.rust-branch }}
      RUST_BACKTRACE: full
      RUST_BIN_DIR: target/${{ matrix.rust-target }}
      TARGET: ${{ matrix.rust-target }}
    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Install Rust ${{ matrix.rust-branch }}
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.rust-branch }}
          components: rustfmt
          profile: minimal

      - name: Clone bittensor repo
        run: git clone https://github.com/opentensor/bittensor.git

      - name: Setup bittensor repo
        working-directory: ${{ github.workspace }}/bittensor
        run: |
          git checkout staging
          python3 -m pip install -e .
          python3 -m pip install torch
          python3 -m pip install pytest
          python3 -m pip install -r requirements/dev.txt

      - name: Run tests
        working-directory: ${{ github.workspace }}/bittensor
        run: |
          pwd
          ls
          CHAIN="e2e_test" LOCALNET_SH_PATH="${{ github.workspace }}/scripts/localnet.sh" pytest tests/e2e_tests/ -s
